org.gradle.jvmargs=-Xmx1G

# Mod
mod_group_id=liltojustice
mod_id=trueadaptivemusic
mod_version=2.7.0
mod_name=True Adaptive Music
mod_description=Experience dynamic music that adapts to what happens in Minecraft!
mod_authors=LilTOJustice
mod_home=https://github.com/LilTOJustice/TrueAdaptiveMusic
mod_issues=https://github.com/LilTOJustice/TrueAdaptiveMusic/issues
mod_source=https://github.com/LilTOJustice/TrueAdaptiveMusic
mod_license=GPL-3.0
mod_icon=assets/trueadaptivemusic/icon.png
archives_base_name=TrueAdaptiveMusic

# Minecraft
minecraft_version=1.21.4
minecraft_version_range=1.21.4

# Common
tam_api_version_range=1.3.*
tam_extensions_version_range=1.1.*

# Fabric
fabric_loader_version=0.19.3
fabric_kotlin_version=1.13.10+kotlin.2.3.20
fabric_api_version=0.119.4+1.21.4
modMenu_version=12.0.0

# NeoForge
forge_kotlin_version=5.12.0
neoforge_version=21.4.157
neoforge_version_range=[21,)
neoforge_loader_version_range=[5.3,)
