modLoader="javafml"
loaderVersion="[47,)"
license="gplv3"

[properties]
"connector:placeholder"=true

[[mods]]
modId="trueadaptivemusic"
version="${mod_version}"
displayName="True Adaptive Music"
authors="LilTOJustice"
description="Experience dynamic music that adapts to what happens in Minecraft!"

[[dependencies.trueadaptivemusic]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.trueadaptivemusic]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.trueadaptivemusic]]
modId="connector"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"